---
spring:
  profiles:
    group:
      local: local_env, secret-dev
---
spring:
  main:
    allow-bean-definition-overriding: true
  config.activate.on-profile: default
  web:
    resources:
      static-locations: classpath:/static/
  locale:
    default: en
    resolver: session
  datasource:
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    #   기존 개발 DB
    url: jdbc:postgresql://postgres-8027951d-9d5e-4e9a-9df5-f7c27e527c8b.cu2h3ll9ayju.ap-northeast-2.rds.amazonaws.com:1625/xniXqDOdrvZo
    username: a4a77124550f
    password: c1ed569d02c942ec
  #   Java Test DB
  #    url: jdbc:postgresql://postgres-5e4a2791-0ac8-4552-8bda-11d73d1cacfe.cu2h3ll9ayju.ap-northeast-2.rds.amazonaws.com:1775/kGArOcNEXAOs
  #    username: d0c5f77e181f
  #    password: 330f299c3cd5ea06522367a05ca4afb3
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none # or update, create-drop, validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/thymeleaf/
    suffix: .html
    enabled: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    always-use-message-format: false

gigya:
  channels:
    default:
      apiKey: "4_lMgx5eUigEBzUwBvUv_Xdw"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    gmapda:
      apiKey: "4_07m4trTc690nw4ETK1AanA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    gmapvd:
      apiKey: "4_V4HXSja5EfsInS6O6j3H7A"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    toolmate:
      apiKey: "4_i_C6Habj4Mige9MKUtogfg"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    sba:
      apiKey: "4_7dCC2lctQpMA85pAGriswQ"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    partnerhub:
      apiKey: "4_dr4wsjFVmeyyioZGZONQVg"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    e2e:
      apiKey: "4_rs8eX994RAoaLGhCYnBm6A"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    mmp:
      apiKey: "4_YgecsrrPedUDYddkNaZ8yQ"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    ets:
      apiKey: "4_Lsvb0HdsDNTQFMVELpSIcA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    edo:
      apiKey: "4_qcCzYKZZ3D-IyyaCwsU2UA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"

loginPage:
  channels:
    toolmate:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    gmapvd:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    gmapda:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    sba:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    partnerhub:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/globalpartnertest/s/home
    edo:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/eu/it/
    mmp:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/MMP/s/login/
    e2e:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/enterprisecustomer/s/login/
    ets:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/mobilecustomer/s/login/




encrypt:
  appKey: kOpHl0VGrA1LZtcIgx02dtZtynl7RPO7dKZ17G/90cg

cds:
  data-source.auto-config.enabled: false

email:
  service:
    url: https://emailsrv-optimistic-shark-ny.cfapps.ap12.hana.ondemand.com
    login: admin
    password: Welcome01
---
spring:
  main:
    allow-bean-definition-overriding: true
  config.activate.on-profile: local_env
  web:
    resources:
      static-locations: classpath:/static/
  locale:
    default: en
    resolver: session
  datasource:
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    #   기존 개발 DB
    #    url: jdbc:postgresql://localhost:1625/xniXqDOdrvZo
    #    username: a4a77124550f
    #    password: c1ed569d02c942ec
    url: jdbc:postgresql://localhost:1775/kGArOcNEXAOs
    username: d0c5f77e181f
    password: 330f299c3cd5ea06522367a05ca4afb3
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:templates/thymeleaf/
    suffix: .html
    enabled: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    always-use-message-format: false
  jpa:
    database: postgresql
    open-in-view: false
    hibernate:
      ddl-auto: none # or update, create-drop, validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

gigya:
  channels:
    default:
      apiKey: "4_lMgx5eUigEBzUwBvUv_Xdw"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    gmapda:
      apiKey: "4_07m4trTc690nw4ETK1AanA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    gmapvd:
      apiKey: "4_V4HXSja5EfsInS6O6j3H7A"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    toolmate:
      apiKey: "4_i_C6Habj4Mige9MKUtogfg"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    sba:
      apiKey: "4_7dCC2lctQpMA85pAGriswQ"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    partnerhub:
      apiKey: "4_dr4wsjFVmeyyioZGZONQVg"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    e2e:
      apiKey: "4_rs8eX994RAoaLGhCYnBm6A"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    mmp:
      apiKey: "4_YgecsrrPedUDYddkNaZ8yQ"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    ets:
      apiKey: "4_Lsvb0HdsDNTQFMVELpSIcA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"
    edo:
      apiKey: "4_qcCzYKZZ3D-IyyaCwsU2UA"
      secretKey: "ayXDsmTkT+mnrCm5tqiUWtrjVrXZKaVh"

loginPage:
  channels:
    toolmate:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    gmapvd:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    gmapda:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    sba:
      landing-page: https://www.sec-toolmate.com/smartpro/login.jsp
    partnerhub:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/globalpartnertest/s/home
    edo:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/eu/it/
    mmp:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/MMP/s/login/
    e2e:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/enterprisecustomer/s/login/
    ets:
      landing-page: https://sec-b2b--fs.sandbox.my.site.com/mobilecustomer/s/login/

encrypt:
  appKey: kOpHl0VGrA1LZtcIgx02dtZtynl7RPO7dKZ17G/90cg

# server:
#   port: 8080
cds:
  data-source.auto-config.enabled: false

email:
  service:
    url: https://emailsrv-optimistic-shark-ny.cfapps.ap12.hana.ondemand.com
    login: admin
    password: Welcome01